Repository team-Edutech/team-Edutech.github.io, pull requests merged in 2022-10, with the labels that each got.

#17 0.0.39
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Features.tsx
  src/components/Intro.tsx
  src/components/Toggle.tsx
  src/pages/Roadmap.tsx
  src/pages/classRoom/ClassRoom.tsx
  src/pages/classRoom/style.ts
  src/pages/course/Course.tsx
Labels: bug

#18 0.0.41
  README.md
  package.json
  public/favicon.ico
  public/favicon.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/supercodinglogo.png
  public/supercodinglogo.svg
Labels: enhancement

#19 0.0.42/ed 241/gnb
  README.md
  public/supercodingbi.png
  public/supercodingbi.svg
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/header/Header.tsx
  src/components/header/style.ts
  src/components/profile/Profile.tsx
  src/components/profile/style.ts
  src/index.css
  src/pages/Feed.tsx
  src/pages/MyClassRoom.tsx
  src/pages/Roadmap.tsx
  src/pages/course/style.ts
  src/static/fonts/AlongSanss2-Black.eot
  src/static/fonts/AlongSanss2-Black.otf
  src/static/fonts/AlongSanss2-Black.woff
  src/static/fonts/AlongSanss2-Black.woff2
  src/static/fonts/AlongSanss2-Bold.eot
  src/static/fonts/AlongSanss2-Bold.woff
  src/static/fonts/AlongSanss2-Bold.woff2
  src/static/fonts/AlongSanss2-Regular.eot
  src/static/fonts/AlongSanss2-Regular.otf
  src/static/fonts/AlongSanss2-Regular.woff
  src/static/fonts/AlongSanss2-Regular.woff2
  src/static/fonts/AlongSanss2-SemiBold.eot
  src/static/fonts/AlongSanss2-SemiBold.otf
  src/static/fonts/AlongSanss2-SemiBold.woff
  src/static/fonts/AlongSanss2-SemiBold.woff2
Labels: enhancement

#21 Feature/ed 247/biz info
  src/components/Footer.tsx
  src/components/bizInfo/BizInfo.tsx
  src/components/bizInfo/style.ts
Labels: enhancement

#25 Feature/sc 266/iamport
  .github/workflows/continouse_deployment._staging.yaml
  README.md
  package.json
  src/components/header/Header.tsx
  src/components/paymentCart/paymentCart.tsx
  src/components/paymentCart/style.ts
  src/components/paymentMethodModal/PaymentMethodModal.tsx
  src/components/paymentPGModal/PaymentPGModal.tsx
  src/components/paymentPGModal/style.ts
  src/config.ts
  src/pages/MyClassRoom.tsx
  src/pages/Roadmap.tsx
  src/pages/classRoom/ClassRoom.tsx
  src/pages/course/Course.tsx
  src/pages/payment/Payment.tsx
  src/pages/payment/style.ts
  src/pages/survey/Survey.tsx
  src/typings/db.ts
Labels: bug, enhancement

#27 SC-269: 홈페이지 하단 BizInfo에 대표번호 추가
  src/components/bizInfo/BizInfo.tsx
Labels: bug, enhancement

#28 SC-269: BizInfo 법인명, 통신판매업 신고번호 수정, 추가
  src/components/bizInfo/BizInfo.tsx
  src/pages/Roadmap.tsx
Labels: enhancement

#29 [SC-270] 코스소개 페이지에서 다른 코스도 결제가능하도록 하기
  .github/workflows/continouse_deployment._dev.yaml
  README.md
  public/courseImage_HTML.png
  public/courseImage_Javascript.png
  public/courseImage_frontend.png
  src/App.tsx
  src/components/CourseCard.tsx
  src/components/paymentCart/paymentCart.tsx
  src/pages/courseIntro/CourseIntro.tsx
  src/pages/courseIntro/style.ts
  src/utils/common.ts
Labels: enhancement

#30 HotFix: Producton 백엔드 연동시 코스소개페이지가 랜더링 되지 않는 이슈 수정
  .github/workflows/continouse_deployment._dev.yaml
  src/pages/courseIntro/CourseIntro.tsx
Labels: bug

#31 SC-271 결제모듈 가상계좌발급 성공시 FE 메세지 변경
  README.md
  src/components/messageModal/MessageModal.tsx
  src/components/paymentButton/PaymentButton.tsx
  src/index.tsx
  src/pages/courseIntro/CourseIntro.tsx
  src/pages/payment/Payment.tsx
  src/repositories/Order.tsx
Labels: bug, enhancement

#32 SC-271 Staging 배포
  README.md
  src/components/messageModal/MessageModal.tsx
  src/components/paymentButton/PaymentButton.tsx
  src/index.tsx
  src/pages/courseIntro/CourseIntro.tsx
  src/pages/payment/Payment.tsx
  src/repositories/Order.tsx
Labels: enhancement

#38 홈화면 디자인 이슈 수정
  public/image/home/logoTile.png
  public/image/home/superCourseBackground.png
  public/image/home/superCurriculumImage2.png
  public/index.html
  public/robots.txt
  src/components/businessCard/BusinessCard.tsx
  src/components/businessCard/style.ts
  src/components/home/SuperCommunity.tsx
  src/components/home/SuperCourse.tsx
  src/components/home/SuperCurriculum.tsx
  src/components/home/SuperManagement.tsx
  src/components/home/superCommunityStyle.ts
  src/components/home/superCourseStyle.ts
  src/components/home/superCurriculumStyle.ts
  src/components/home/superManagementStyle.ts
  src/components/home/superReivewStyle.ts
  src/components/home/superResumeStyle.ts
  src/static/image/checkIndicatorLarge.png
  src/static/image/home/superCurriculumImagePlayCircle.png
  src/static/image/home/superManagementMobile.png
  src/static/image/supercodinglogoL.png
Labels: bug, enhancement

#43 상품 페이지 모바일 디자인 시안 적용
  public/image/product/logoTileMobile.png
  public/image/product/otMobile.png
  public/image/product/supercodingbandMobile.png
  public/image/product/whyMobile.png
  src/components/Footer/style.ts
  src/components/header/style.ts
  src/components/home/SuperCourse.tsx
  src/components/home/superCommunityStyle.ts
  src/components/home/superCourseStyle.ts
  src/components/home/superCurriculumStyle.ts
  src/components/home/superManagementStyle.ts
  src/components/home/superReivewStyle.ts
  src/components/product/BodyFeatures.tsx
  src/components/product/BodyManagement.tsx
  src/components/product/BodyProgram.tsx
  src/components/product/BodyTop.tsx
  src/components/product/Bottom.tsx
  src/components/product/FAQ.tsx
  src/components/product/Top.tsx
  src/components/product/bodyFeatureStyle.ts
  src/components/product/bodyManagementStyle.ts
  src/components/product/bodyProgramStyle.ts
  src/components/product/bodyTopStyle.ts
  src/components/product/bottomStyle.ts
  src/components/product/faqStyle.ts
  src/components/product/topStyle.ts
  src/components/timeBanner/style.ts
  src/pages/product/Product.tsx
  src/static/image/product/boxArrowDown.png
  src/static/image/product/boxArrowUp.png
  src/static/image/product/interviewMobile.png
  src/static/image/product/ot.png
  src/static/image/product/otMobile.png
  src/static/image/product/portfolioMobile.png
  src/static/image/product/recommendationMobile.png
  src/static/image/product/resumeMobile.png
  src/static/image/product/review.png
  src/static/image/product/reviewMobile.png
  src/static/image/product/slashMobile.png
  src/static/image/product/tableMobile.png
Labels: enhancement

#44 내강의실/강의시청 페이지 레이아웃 수정
  src/components/courseEpisode/style.ts
  src/pages/myClassRoom/MyClassRoom.tsx
  src/pages/myClassRoom/style.ts
  src/pages/videoRoom/VideoRoom.tsx
  src/pages/videoRoom/style.ts
Labels: enhancement

#47 무료 강의 페이지 모바일 디자인 시안 적용
  package.json
  public/image/freeCourse/mentorBackgroundMobile.png
  public/image/freeCourse/reviewCardMobile.png
  src/App.tsx
  src/components/Footer/style.ts
  src/components/authForm/AuthFormModal.tsx
  src/components/authMethod/AuthMethodModal.tsx
  src/components/ddayTimer/DdayTimer.tsx
  src/components/ddayTimer/style.ts
  src/components/freeCourse/BodyBottom.tsx
  src/components/freeCourse/BodyMiddel.tsx
  src/components/freeCourse/BodyTop.tsx
  src/components/freeCourse/Bottom.tsx
  src/components/freeCourse/EventSection.tsx
  src/components/freeCourse/Top.tsx
  src/components/freeCourse/bodyBottomStyle.ts
  src/components/freeCourse/bodyMiddle.ts
  src/components/freeCourse/bodyTopStyle.ts
  src/components/freeCourse/bottomStyle.ts
  src/components/freeCourse/eventSectionStyle.ts
  src/components/freeCourse/topStyle.ts
  src/components/home/SuperCourse.tsx
  src/components/home/superCourseStyle.ts
  src/components/paginationSlide/PaginationSlide.tsx
  src/components/paginationSlide/paginationSlide.ts
  src/components/timeBanner/TimeBanner.tsx
  src/components/timeBanner/style.ts
  src/static/image/apple.png
  src/static/image/facebook.png
  src/static/image/naver.png
  yarn.lock
Labels: bug, enhancement
